Django9/src/Django9/urls.py
from django.contrib import admin
from django.urls import path, include
#
from bookmark.views import *
#urlpatterns : 등록된 URL을 관리하는 변수
#URL등록시 path()함수를 이용해 urlpatterns의 요소를 추가
#path(URL주소(문자열), 뷰함수이름)
#웹서버 실행시 나오는 도메인 주소(127.0.0.1:8000)은 기본값 부여
urlpatterns = [
    #http://127.0.0.1:8000/admin 로 접근시 관리자 사이트 호출
    path('admin/', admin.site.urls),
    #http://127.0.0.1:8000 로 접근시 index함수 호출
    path('', index, name='index'  ),
    #http://127.0.0.1:8000/list 로 접근시 booklist 함수 호출
    path('list/', booklist, name='booklist' ),
    #http://127.0.0.1:8000/1/숫자데이터/ 로 접근시 bookdetail함수 호출
    #이 때, 숫자데이터에 값은 bookmark_id 매개변수에 들어감
    path('<int:bookmark_id>/', bookdetail),
    #주소에 http://127.0.0.1:8000/vote 가 포함이 되어있으면, vote폴더안에
    #있는 urls.py에 등록된 url을 사용
    path('vote/', include("vote.urls")),
    #주소에 http://127.0.0.1:8000/auth/ 가 적힌 URL들은
    #customlogin폴더에 있는 urls파일이 관리
    path('auth/', include("customlogin.urls")),
    
    # 'social'이라는 이름으로 그룹명을 변경 (app_name 변수 무시)
    path('oauth/', include("social_django.urls", namespace="social")),
    path('blog/', include("blog.urls"))
]
#이미지 관련 처리를 위해 pillow 모듈 설치
from django.conf import settings
from django.conf.urls.static import static
#URL 요청과 실제파일 매칭을 등록
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django9/src/blog/urls.py
'''
Created on 2018. 10. 6.

@author: user
'''
from django.urls import path
from .views import *
app_name = 'blog'
urlpatterns = [
    #뷰 클래스를 url 등록할 때, 뷰클래스명.as_view()로 등록함
    path('', Index.as_view(), name='index' ),
    #DetailView는 특정 객체를 찾기위해 pk(id 변수) 또는 slug 변수를 사용함
    #모델클래스의 기본키로 설정되있는 변수의 이름으로 URL 값을 넘겨줌
    path('<int:pk>/', Detail.as_view(), name='detail' ),
    path('postR/', PostRegister.as_view(), name='registerP'),
    path('search/',searchP, name='search')
    ]










Django9/src/blog/models.py
from django.db import models

# Create your models here.
#카테고리
class PostType(models.Model):
    name = models.CharField('카테고리', max_length=100)
    def __str__(self):
        return self.name
#from django.contrib.auth.models import User
from django.conf import settings
#글 (글제목, 글내용, 작성자, 작성일, 카테고리(외래키))
class Post(models.Model):
    #카테고리(type) : ForeignKey.PostType 모델클래스와 연동
    type = models.ForeignKey(PostType, on_delete=models.PROTECT)
    #외래키 설정 시 on)delete에 넣을 수 있는 값
    #models.CASCADE :연결된 객체가 삭제되면 다같이 삭제되는 것
    #models.PROTECT : 연결된 객체가 삭제되지 않도록 막는 역할
    #models.SET_NULL : 연결된 객체가 삭제되면 null값을 가지는 역할
    #models.SET_DEFAULT : 연결된 객체가 삭제되면 기본 객체와 연결되는 역할
    #models.SET() : 연결된 객체가 삭제되면 특정함수로 새로운 객체를 찾아 연결하는 역할
    #글 제목(headline) : Charfield.글자수 200자 제한
    headline = models.CharField('제목', max_length=200)
    #글 내용(content) : TextField.
    content = models.TextField('내용')
    #작성자(author) : ForeignKey. Django.auth.models.User 모델클래스와 연동
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    #작성일(pub_date) : DateTimeField. auto_now_add=True
    pub_date = models.DateTimeField('작성일', auto_now_add=True)
    class Meta: #모델 클래스도 Meta 클래스를 정의해서 추가적인 정렬, 정보를 제공
        #ordering : 모델클래스에서 사용하는 변수명을 입력해 정렬하는 방식을 명시
        #기본적으로 오름차순으로 정렬함. 변수명앞에'_' 기호를 붙으면 내림차순으로 정렬
        ordering = ['-id']
        #관리자 사이트에서 해당 모데클래스 이름을 변경
        verbose_name = '글'

#이미지 저장 Post(외래키), 이미지 저장 공간
class PostImage(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE)
    #ImageField() : 이미지의 경로를 저장하는 필드
    #upload_to : 이미지 저장시 어떤 폴더이름으로 분류할지 지정하는 매개변수
    # %Y : 해당 서버의 년도
    # %m : 해당 서버의 월
    # %d : 해당 서버의 일
    image = models.ImageField('이미지파일', upload_to = "images/%Y/%m/%d")
    #객체 삭제 시 image에 저장한 파일 경로의 파일 삭제 처리
    def delete(self, using=None, keep_parents=False):
        #image변수에 저장된 경로의 파일을 지우는 작업
        #왜? PostImage객체가 지워질때 image변수가 가르키는 경로의 파일이 지워지지 않음
        #ImageField/FileField 사용시 객체가 삭제될때 호출되는 delete함수를 오버라이딩해서
        #해당 객체를 수동으로 지우는 작업(delete함수 호출)을 수행해야 함
        self.image.delete()
        return models.Model.delete(self, using=using, keep_parents=keep_parents)
#파일 저장
class PostFile(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    #FileField() : 파일의 경로를 저장하는 필드
    file = models.FileField('파일', upload_to = 'files/%Y/%m/%d')
    #객체 삭제 시 file에 저장한 파일 경로에 해당하는 파일을 삭제하는 처리
    def delete(self, using=None, keep_parents=False):
        self.file.delete()
        return models.Model.delete(self, using=using, keep_parents=keep_parents)
    
    

Django9/src/blog/forms.py
'''
Created on 2018. 10. 6.

@author: user
'''
from django.forms.models import ModelForm
from django import forms
from .models import Post
class PostForm(ModelForm):
    #사용자가 파일데이터를 주지않더라도 보낼수있도록허용
    files = forms.FileField(required = False, 
                            widget=forms.ClearableFileInput(attrs={'multiple':True}))
    images = forms.ImageField(required = False,
                              widget=forms.ClearableFileInput(attrs={'multiple':True}))
    class Meta:
        model = Post
        fields = ['type', 'headline','content']
    field_order = ['type', 'headline','files','images','content']
        

Django9/src/blog/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from .models import Post
from django.contrib.auth.mixins import LoginRequiredMixin
from blog.models import PostImage, PostFile
#제네릭뷰 : 장고에서 제공하는 여러가지 기능을 수행하는 뷰클래스
#Class 뷰이름(제네릭뷰 상속):
#상속받은 제네릭뷰클래스의 변수/메소드를 수정해 사용
#단, 해당 제네릭뷰가 어떤 기능을 수행하는지 정확히 알아야함
#어떤 변수/메소드를 사용할 수 있는지 알아야함
#ListView : 특정 객체의 목록을 다루는 기능을 하는 뷰클래스
class Index(ListView):
    #template_name : HTML 경로를 문자열로 저장
    template_name = 'blog/index.html'
    #model         : 모델클래스를 저장
    model = Post
    #context_object_name : 템플릿에 넘겨줄 리스트 이름
    context_object_name = 'post_list'
    #paginate_by : 한페이지에 몇개의 객체가 보여질지 정수값을 저장
    paginate_by = 5
    
from django.views.generic.detail import DetailView
#DetailView : 특정 모델클래스의 하나의 객체를 테플릿에게 전달할때 사용하는 뷰클래스
class Detail(DetailView):
    template_name= 'blog/detail.html'
    model = Post
    context_object_name = 'obj'
from django.views.generic.edit import FormView,View    
from .forms import PostForm
from django.http.response import HttpResponseRedirect
from django.urls.base import reverse
#FormView : 특정 폼 클래스를 템플릿에게 전다라고 GET/POST을 나눠서 처리할때 사용하는 뷰클래스
#LoginRequiredMixin : 사용자의 로그인 유무를 판별해 비로그인상태의 사용자는 로그인페이지로 변경
class PostRegister(LoginRequiredMixin, FormView):  
    form_class= PostForm#폼클래스명
    template_name = 'blog/postRegister.html'
    context_object_name = 'form'
    #사용자가 POST방식으로 요청했을때 데이터 유효성을 검사한 뒤 호출되는 메소드
    def form_valid(self, form):
        obj = form.save(commit=False) #Post 객체로 변환
        #뷰클래스의 slef.request == 뷰함수의 request 매개변수
        obj.author = self.request.user#유저정보 채우기
        obj.save()                      #객체를 데이터베이스에 저장
        #사용자가 저장요청한 이미지파일, 파일 객체 생성
        #name이'images'인 파일데이터를 추출하는 방법
        for f in self.request.FILES.getlist('images'):
            #PostImage 모델클래스의 객체 생성
            #객체 생성시 각 변수에 값을 대입
            image = PostImage(post=obj,image=f)
            #image = PostImage()
            #image.post = obj
            #image.image=f
            image.save()
        #사용자가 준 파일 정보에서 'files' 라벨로 온 데이터를 추출
        for f in self.request.FILES.getlist('files'):
            #PostFile 모델클래스의 객체 생성
            file = PostFile(post=obj,file=f)
            file.save()
        #완성한 글의 URL로 이동
        return HttpResponseRedirect(reverse('blog:detail', args=(obj.id,)))
    
#검색기능 구현
def searchP(request):
    #<input type="input" name="query" />
    #GET요청으로 온 데이터에 name이 'query'인 데이터를 추출
    #웹요청으로 온 데이터는 무조건 문자열 처리가 됨
    q = request.GET.get('query','') #'query'로 데이터가 안온경우, 빈문자열('')을 반환
    #q에 들어있는 문자열을 포함한 제목을 가진 Post 객체를 검색
    #contains 명령: 해당변수에 문자열안에 우변값이 포함되어있는 확인
    list = Post.objects.filter(headline__contains= q)
    return render(request, 'blog/search.html', {'list':list})
    
    
    
    
    
    
    
    
    
    

Django9/src/blog/templates/blog/booklist.html
{% extends 'base.html' %}
{% block title %}
메인 페이지로 가기
{% endblock %}
{% block content %}
	<h1>BookMark 객체 출력</h1>
	<table>
		<tr>
			<th> id</th>
			<th> bookname</th>
			<th> bookurl</th>
		</tr>
		{# 뷰에서 넘겨받은 list 변수를 이용해 반복문 돌리기 #}
		{% for obj in list %}
		{# 반복문 안에서 객체를 가지고 있는 변수 :obj #}
		{# obj 변수는 BookMark 모델클래스 객체이므로 .(점)연산자로 객체 안에 있는 변수를 사용#}
		<tr>
			<td><a href="{% url 'bookdetail' obj.id %}">{{  obj.id  }}</a></td>
			<td> <a href="{{obj.bookurl}}">{{  obj.bookname  }}</a></td>
			<td>{{  obj.bookurl  }}</td>
		</tr>
		{% endfor %}
	</table>
	<a href="{% url 'index' %}">메인페이지로 가기</a>
{% endblock %}

Django9/src/blog/templates/blog/detail.html
{% extends 'base.html' %}
{% block title %}
	나만의 블로그 - {{ obj.headline }}
{% endblock %}
{% block content %}
	<table width="100%">
		<tr>
			<th> 제목</th>
			<th> {{ obj.author }}/{{obj.pub_date }}</th>
		</tr>
		<tr>
			<th colspan="2">
				{# 해당 Post 객체와 연결된 PostImage, PostFile 객체를 출력 #}
				{% for i in obj.postimage_set.all %}
					<img src="{{ i.image.url }}" width=30%>
				{% endfor %}
				
				{% for file in obj.postfile_set.all%}
					<a href="{{ f.file.url }}" download>다운로드</a>
				{% endfor%}
				<pre> {{ obj.content }}</pre>
			</th>
		</tr>
	
	</table>
	{# disqus 사이트의 댓글 연동 #}
	{% load disqus_tags %}
	{% disqus_show_comments %}
{% endblock %}










Django9/src/blog/templates/blog/postRegister.html
{% extends 'base.html' %}
{% block title %}
나만의 블로그 - 글 등록
{% endblock%}

{% block content %}
<form action ="" ,method="POST" enctype="multipart/form-data">
	{% csrf_token %}
	<table>
	{{ form.as_table }} 
	</table>
	<input type="submit" value="글쓰기">
</form>
{% endblock %}

Django9/src/blog/templates/blog/search.html
{% extends 'base.html' %}
{% block title %}
나만의 블로그
{% endblock %}

{% block content %}
<h3>검색 결과</h3>
<table style="width:100%">
	<tr>
		<th> 글번호 </th>
		<th> 제목 </th>
		<th> 작성자 </th>
		<th> 작성일 </th>
	</tr>
	{% for post in post_list %}
		<tr>
			<th>{{ post.id }}</th>
			<th>
				<a href="{% url 'blog:detail' post.id %}">{{ post.headline }}</a>
			</th>
			<th>{{ post.author }}</th>
			<th>{{ post.pub_date }}</th>
		</tr>
	{% endfor %}
</table>
<!-- 검색창 -->
<form action="" method="GET">
	{% csrf_token %}
	<input type="text" name='query'>
	<input type='submit' value='검색'>
</form>

{% endblock %}







