Django9/src/Django9/urls.py
from django.contrib import admin
from django.urls import path, include
#
from bookmark.views import *
#urlpatterns : 등록된 URL을 관리하는 변수
#URL등록시 path()함수를 이용해 urlpatterns의 요소를 추가
#path(URL주소(문자열), 뷰함수이름)
#웹서버 실행시 나오는 도메인 주소(127.0.0.1:8000)은 기본값 부여
urlpatterns = [
    #http://127.0.0.1:8000/admin 로 접근시 관리자 사이트 호출
    path('admin/', admin.site.urls),
    #http://127.0.0.1:8000 로 접근시 index함수 호출
    path('', index, name='index'  ),
    #http://127.0.0.1:8000/list 로 접근시 booklist 함수 호출
    path('list/', booklist, name='booklist' ),
    #http://127.0.0.1:8000/1/숫자데이터/ 로 접근시 bookdetail함수 호출
    #이 때, 숫자데이터에 값은 bookmark_id 매개변수에 들어감
    path('<int:bookmark_id>/', bookdetail),
    #주소에 http://127.0.0.1:8000/vote 가 포함이 되어있으면, vote폴더안에
    #있는 urls.py에 등록된 url을 사용
    path('vote/', include("vote.urls")),
    #주소에 http://127.0.0.1:8000/auth/ 가 적힌 URL들은
    #customlogin폴더에 있는 urls파일이 관리
    path('auth/', include("customlogin.urls")),
    
    # 'social'이라는 이름으로 그룹명을 변경 (app_name 변수 무시)
    path('oauth/', include("social_django.urls", namespace="social")),
    path('blog/', include("blog.urls"))
]
#이미지 관련 처리를 위해 pillow 모듈 설치
from django.conf import settings
from django.conf.urls.static import static
#URL 요청과 실제파일 매칭을 등록
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django9/src/blog/urls.py
'''
Created on 2018. 10. 6.

@author: user
'''
from django.urls import path
from .views import *
app_name = 'blog'
urlpatterns = [
    #뷰 클래스를 url 등록할 때, 뷰클래스명.as_view()로 등록함
    path('', Index.as_view(), name='index' ),
    #DetailView는 특정 객체를 찾기위해 pk(id 변수) 또는 slug 변수를 사용함
    #모델클래스의 기본키로 설정되있는 변수의 이름으로 URL 값을 넘겨줌
    path('<int:pk>/', Detail.as_view(), name='detail' ),
    path('postR/', PostRegister.as_view(), name='registerP'),
    path('search/',searchP, name='search')
    ]










Django9/src/bookmark/models.py
from django.db import models

# Create your models here.
#모델(Model):데이터베이스에 데이터를 저장할 때, 어떠한 형식으로
#           저장할지 관리하는 부분
#models.Model :장고에서 제공하는 Modle 클래스, 해당 클래스를
#상속받아야만 Model의 기능을 할 수 있음
#북마크 모델 클래스
#북마크 이름, URL 주소
class Bookmark(models.Model):
    #해당 모델클래스에 저장할 값을 정의할 때, 클래스 내의 변수 정의
    #변수 정의 시 xxxxField 클래스의 객체를 변수에 대입해 어떤 값을 저장할지
    #정의함
    #CharField() : 글자수 제한이 있는 문자열을 저장하는 공간 정의
    #URLField() : 인터넷 주소를 저장하는 공간 정의
    bookname = models.CharField(max_length=100)
    bookurl = models.URLField()
    #객체를 출력할 때 표현방식을 처리하는 함수
    def __str__(self):
        return self.bookname
    
    
    
    
    

Django9/src/bookmark/views.py
from django.shortcuts import render
from .models import *
# Create your views here.
#View : 사용자의 요청에 따라 처리하고, HTML파일이나 새로운 URL주소를 전송함
#View 정의시 함수 / 클래스 형태로 정의
#View 함수 정의시 첫번째 매개변수로 request 변수를 사용함
#request : 웹 클라이언트의 요청에 대한 정보를 가지고 있음
#ex) 로그인 정보, FORM(입력양식) 값, 등
#메인페이지
def index(request):
    #render(request, HTML문서 위치, 탬플릿에 전달할 값)
    #현재 요청을 한 웹 클라이언트에게 bookmark폴더에 있는 index.html 파일을 전송
    #사전형:{키 : 값,} 키: 숫자, 문자열 값:상수,문자열,변수,객체,리스트,튜플,사전
    #변수명[키]
    #탬플릿에 사전형 데이터를 전송하면 키에 해당하는 값을 변수처럼 사용
    return render(request, 'bookmark/index.html', {'hello':'world', 'list':[1,2,3]})
    
    
#BookMark 모델클래스에 저장된 객체들을 HTML문서에 출력
def booklist(request) :
    #BookMark 객체검색
    obj = Bookmark.objects.all()
    #탬플릿 전달
    return render(request, 'bookmark/booklist.html',{'list': obj})
    
#웹 클라이언트가 선택한 북마크 객체를 화면에 출력하는 뷰함수
#bookmark_id : 해당 id값을 가진 객체를 추출하기 위한 매개변수
def bookdetail(request, bookmark_id ):
    #get함수 : 해당 모델클래스에서 하나의 객체를 추출
    #get함수의 인자값은 해당 모델클래스의 변수명을 사용

    #Bookmark 모델클래스의 객체들 중 id 변수에 들어있는 값이
    #bookmark_id 값과 동일한 객체 한개를 추출
    obj = Bookmark.objects.get(id = bookmark_id)    
    #해당조건을 만족하는 객체
    #만약, 해당 조건을 만족하는 객체가 없는경우 -> 서버오류 판단해 500번대 에러가 뜸
    return render(request, 'bookmark/bookdetail/html',
                  { 'obj': obj})
    
    
    
    
    
    
    
    

Django9/src/bookmark/templates/bookmark/bookdetail.html
{% extends 'base.html' %}
{% block title %}
북마크 객체 상세 페이지
{% endblock %}
{% block content %}
	{# 뷰에서 북마크 객체를 obj 변수에 넣어 전달 #}
	<h1>북마크 객체 상세페이지</h1>
	<u1>
		<li>ID : {{obj.id}}</li>
		<li>bookname :{{obj.bookname}}</li>
		<li>bookurl :{{obj.bookurl}}</li>

	</u1>
{% endblock %}

Django9/src/bookmark/templates/bookmark/booklist.html
{% extends 'base.html' %}
{% block title %}
메인 페이지로 가기
{% endblock %}
{% block content %}
	<h1>BookMark 객체 출력</h1>
	<table>
		<tr>
			<th> id</th>
			<th> bookname</th>
			<th> bookurl</th>
		</tr>
		{# 뷰에서 넘겨받은 list 변수를 이용해 반복문 돌리기 #}
		{% for obj in list %}
		{# 반복문 안에서 객체를 가지고 있는 변수 :obj #}
		{# obj 변수는 BookMark 모델클래스 객체이므로 .(점)연산자로 객체 안에 있는 변수를 사용#}
		<tr>
			<td><a href="{% url 'bookdetail' obj.id %}">{{  obj.id  }}</a></td>
			<td> <a href="{{obj.bookurl}}">{{  obj.bookname  }}</a></td>
			<td>{{  obj.bookurl  }}</td>
		</tr>
		{% endfor %}
	</table>
	<a href="{% url 'index' %}">메인페이지로 가기</a>
{% endblock %}

Django9/src/bookmark/templates/bookmark/index.html
{% extends 'base.html' %}
{% block title %}
북마크 어플리케이션
{% endblock %}
{% block content%}
	<h1>장고 북마크 어플리케이션</h1>
	<p>메인페이지입니다</p>
	{# 파이썬 코드 주석 #}
	<p>뷰 함수에서 전달받은 hello 변수 값 출력 : {{ hello }}</p>
	<ol>
	{% for i in list  %}
		<li> {{ i }} </li>
	{%endfor %}

<br>
<form action="{% url 'blog:search' %}" method="GET">
	{% csrf_token %}
	<input type="text" name='query'>
	<input type='submit' value='검색'>
</form>

{% endblock%}